//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDebitiV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class debitiEntities : DbContext
    {
        public debitiEntities()
            : base("name=debitiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<friendlist> friendlist { get; set; }
        public virtual DbSet<paymentrequest> paymentrequest { get; set; }
        public virtual DbSet<request> request { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
