//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDebitiV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class friendlist
    {
        public int user_ID { get; set; }
        public int user_ID1 { get; set; }
        public string Stato { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
