//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDebitiV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentrequest
    {
        public int ID { get; set; }
        public int Request_ID { get; set; }
        public float Credito { get; set; }
        public string Stato { get; set; }
    
        public virtual request request { get; set; }
    }
}
