//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDebitiV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request()
        {
            this.paymentrequest = new HashSet<paymentrequest>();
        }
    
        public int ID { get; set; }
        public int ID_mandante { get; set; }
        public int ID_ricevente { get; set; }
        public float Credito { get; set; }
        public string Stato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paymentrequest> paymentrequest { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
